"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

num_array = [1, 2]
i = 0
while num_array[-1] <= 4000000:
    num_array.append(num_array[i] + num_array[i + 1])
    i += 1
evens = list(filter(lambda x: x % 2 == 0, num_array))
print(sum(evens))
